services:
  # postgres database
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgress_admin
      POSTGRES_PASSWORD: postgress_admin
      POSTGRES_DB: simplified_stock_market
      PGDATA: /var/lib/postgresql/data/pg18
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    # needed for db-migrate
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgress_admin -d simplified_stock_market" ]
      interval: 2s
      timeout: 2s
      retries: 5

  # Node.js app (Production mode)
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgress_admin:postgress_admin@db:5432/simplified_stock_market
      - NODE_ENV=development
    depends_on:
      # a health check for app - runs when the db is ready
      db:
        condition: service_healthy

volumes:
  pgdata:
